#model:
name: effnet
device: cuda
input_channels: 1  # Grayscale
num_classes: 1  # Single class for person detection
pretrained: true
transform:
  input_size: [224, 224]
loss:
  cls_loss_weight: 0.5 
  box_loss_weight: ${eval:1 - model.loss.cls_loss_weight}